(function(){
  const db = window.skyeSupabase;
  if (!db) { alert('SKYE could not initialise its secure connection. Please refresh the page and try again.'); return; }
  const PENDING_KEY='skye_pending_company';
  const APP_URL='https://geeskye.github.io/skye-hse-copilot/index.html';
  const DASHBOARD_URL='https://geeskye.github.io/skye-hse-copilot/dashboard.html';
  async function getMembership(){const {data,error}=await db.rpc('get_my_company_workspace');if(error)throw error;if(!data||!data.length)return null;const row=data[0];return {company_id:row.company_id,role:row.role,companies:{name:row.company_name}};}
  async function ensureWorkspace(){let membership=await getMembership();if(membership)return membership;const pending=localStorage.getItem(PENDING_KEY);if(!pending)return null;let pendingData;try{pendingData=JSON.parse(pending)}catch(_){pendingData=null}const companyName=pendingData&&pendingData.company?pendingData.company.trim():'';if(!companyName)return null;const {data:companyId,error:createError}=await db.rpc('create_company_workspace',{p_company_name:companyName});if(createError)throw createError;localStorage.removeItem(PENDING_KEY);membership=await getMembership();return membership||({company_id:companyId,role:'owner',companies:{name:companyName}});}
  function goDashboard(){window.location.href=DASHBOARD_URL;}
  window.signIn=async function(){const email=document.getElementById('email').value.trim();const password=document.getElementById('password').value;const companyInput=document.getElementById('company').value.trim();if(!email||!password){alert('Enter your email address and password.');return;}const button=document.querySelector('#login .primary');if(button){button.disabled=true;button.textContent='Signing in…';}try{const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;const membership=await ensureWorkspace();if(!membership){await db.auth.signOut();throw new Error('Your account is authenticated, but it is not linked to a SKYE company workspace yet.');}const companyName=membership.companies&&membership.companies.name?membership.companies.name:'Company';if(companyInput&&companyInput.toLowerCase()!==companyName.toLowerCase()){await db.auth.signOut();throw new Error('The company entered does not match the workspace linked to this account.');}goDashboard();}catch(err){console.error(err);alert(err.message||'Unable to sign in.');}finally{if(button){button.disabled=false;button.textContent='Sign in to SKYE';}}};
  window.createAccount=async function(){const company=document.getElementById('company').value.trim();const admin=document.getElementById('admin').value.trim();const email=document.getElementById('email').value.trim();const password=document.getElementById('password').value;const confirm=document.getElementById('confirm').value;if(!company||!admin||!email||!password||!confirm){alert('Please complete all fields.');return;}if(!email.includes('@')||!email.includes('.')){alert('Please enter a valid email address.');return;}if(password.length<8||!/[0-9]/.test(password)){alert('Password must be at least 8 characters and contain a number.');return;}if(password!==confirm){alert('Passwords do not match.');return;}const button=document.querySelector('#formView .primary');if(button){button.disabled=true;button.textContent='Creating account…';}try{localStorage.setItem(PENDING_KEY,JSON.stringify({company,admin,email}));const {data,error}=await db.auth.signUp({email,password,options:{data:{full_name:admin},emailRedirectTo:APP_URL}});if(error)throw error;if(data.session&&data.user){const membership=await ensureWorkspace();if(!membership)throw new Error('Account created, but the company workspace could not be created yet.');localStorage.removeItem(PENDING_KEY);}document.getElementById('createdCompany').textContent=company;const msg=document.getElementById('successMessage');if(msg)msg.textContent=data.session?'Your SKYE account and private company workspace are ready.':'Your account has been created. Confirm your email, then sign in. Your private company workspace will be created automatically on first sign-in.';document.getElementById('formView').style.display='none';document.getElementById('successView').style.display='block';}catch(err){console.error(err);localStorage.removeItem(PENDING_KEY);alert(err.message||'Unable to create the account.');}finally{if(button){button.disabled=false;button.textContent='Create company workspace';}}};
  window.logout=async function(){await db.auth.signOut();window.location.href=APP_URL;};
  document.addEventListener('DOMContentLoaded',async function(){const {data}=await db.auth.getSession();if(!data.session)return;try{const membership=await ensureWorkspace();if(membership&&document.getElementById('login'))goDashboard();}catch(err){console.error('Session restore failed:',err);await db.auth.signOut();}});
})();
