(function(){
  const db = window.skyeSupabase;
  if (!db) { alert('SKYE could not initialise its secure connection. Please refresh the page and try again.'); return; }
  const PENDING_KEY='skye_pending_company';
  const APP_URL='https://geeskye.github.io/skye-hse-copilot/index.html';
  const DASHBOARD_URL='https://geeskye.github.io/skye-hse-copilot/dashboard.html';
  async function getMembership(){const {data,error}=await db.rpc('get_my_company_workspace');if(error)throw error;if(!data||!data.length)return null;const row=data[0];return {company_id:row.company_id,role:row.role,companies:{name:row.company_name}};}
  async function ensureWorkspace(){let membership=await getMembership();if(membership)return membership;const pending=localStorage.getItem(PENDING_KEY);if(!pending)return null;let pendingData;try{pendingData=JSON.parse(pending)}catch(_){pendingData=null}const companyName=pendingData&&pendingData.company?pendingData.company.trim():'';if(!companyName)return null;const {data:companyId,error:createError}=await db.rpc('create_company_workspace',{p_company_name:companyName});if(createError)throw createError;localStorage.removeItem(PENDING_KEY);membership=await getMembership();return membership||({company_id:companyId,role:'owner',companies:{name:companyName}});}
  function goDashboard(){window.location.href=DASHBOARD_URL;}
  window.signIn=async function(){const email=document.getElementById('email').value.trim();const password=document.getElementById('password').value;const companyInput=document.getElementById('company').value.trim();if(!email||!password){alert('Enter your email address and password.');return;}const button=document.querySelector('#login .primary');if(button){button.disabled=true;button.textContent='Signing in…';}try{const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;const membership=await ensureWorkspace();if(!membership){await db.auth.signOut();throw new Error('Your account is authenticated, but it is not linked to a SKYE company workspace yet.');}const companyName=membership.companies&&membership.companies.name?membership.companies.name:'Company';if(companyInput&&companyInput.toLowerCase()!==companyName.toLowerCase()){await db.auth.signOut();throw new Error('The company entered does not match the workspace linked to this account.');}goDashboard();}catch(err){console.error(err);alert(err.message||'Unable to sign in.');}finally{if(button){button.disabled=false;button.textContent='Sign in to SKYE';}}};
  window.createAccount=async function(){const company=document.getElementById('company').value.trim();const admin=document.getElementById('admin').value.trim();const email=document.getElementById('email').value.trim();const password=document.getElementById('password').value;const confirm=document.getElementById('confirm').value;if(!company||!admin||!email||!password||!confirm){alert('Please complete all fields.');return;}if(!email.includes('@')||!email.includes('.')){alert('Please enter a valid email address.');return;}if(password.length<8||!/[0-9]/.test(password)){alert('Password must be at least 8 characters and contain a number.');return;}if(password!==confirm){alert('Passwords do not match.');return;}const button=document.querySelector('#formView .primary');if(button){button.disabled=true;button.textContent='Creating account…';}try{localStorage.setItem(PENDING_KEY,JSON.stringify({company,admin,email}));const {data,error}=await db.auth.signUp({email,password,options:{data:{full_name:admin},emailRedirectTo:APP_URL}});if(error)throw error;if(data.session&&data.user){const membership=await ensureWorkspace();if(!membership)throw new Error('Account created, but the company workspace could not be created yet.');localStorage.removeItem(PENDING_KEY);}document.getElementById('createdCompany').textContent=company;const msg=document.getElementById('successMessage');if(msg)msg.textContent=data.session?'Your SKYE account and private company workspace are ready.':'Your account has been created. Confirm your email, then sign in. Your private company workspace will be created automatically on first sign-in.';document.getElementById('formView').style.display='none';document.getElementById('successView').style.display='block';}catch(err){console.error(err);localStorage.removeItem(PENDING_KEY);alert(err.message||'Unable to create the account.');}finally{if(button){button.disabled=false;button.textContent='Create company workspace';}}};
  window.logout=async function(){await db.auth.signOut();window.location.href=APP_URL;};
  document.addEventListener('DOMContentLoaded',async function(){const {data}=await db.auth.getSession();if(!data.session)return;try{const membership=await ensureWorkspace();if(membership&&document.getElementById('login'))goDashboard();}catch(err){console.error('Session restore failed:',err);await db.auth.signOut();}});
})();

/* Landing page visual system — green offshore SKYE theme. */
(function(){
  if(location.pathname.endsWith('/index.html') || location.pathname.endsWith('/')){
    if(document.getElementById('skye-green-theme')) return;
    const s=document.createElement('style');s.id='skye-green-theme';
    s.textContent=`
:root{--skye-green:#176b4d;--skye-dark:#0b2b21;--skye-deep:#061d16;--skye-pale:#e8f2ec;--skye-paper:#f5f8f6;--skye-line:#d4e1da;--skye-muted:#60736b}
body{background:var(--skye-paper)!important;color:#123126!important}
.nav{background:rgba(245,248,246,.95)!important;border-bottom:1px solid var(--skye-line)!important}.brand{color:#123126!important}.brand span{color:var(--skye-green)!important}.navlinks a{color:#123126!important}.navcta{background:var(--skye-dark)!important;color:#fff!important;border-radius:999px!important}
.hero{background:linear-gradient(90deg,rgba(4,29,21,.98) 0%,rgba(7,39,28,.93) 42%,rgba(8,45,32,.68) 72%,rgba(8,45,32,.55) 100%),url('assets/offshore-bg.jpg') center/cover no-repeat!important;min-height:760px!important}
.hero:after{content:"";position:absolute;inset:0;background:linear-gradient(135deg,rgba(23,107,77,.22),transparent 48%,rgba(3,24,17,.22));pointer-events:none}.hero-copy{z-index:2}.hero .eyebrow{color:#9bc7b2!important}.hero h1{color:#f8fbf9!important}.hero h1 em{color:#a9d4bd!important}.hero-sub{color:#d4e2db!important}.btn{border-color:#a9cbbb!important}.btn.dark{background:#f4f8f6!important;color:#0b2b21!important;border-color:#f4f8f6!important}.btn.light{background:rgba(8,43,31,.28)!important;color:#fff!important}.hero-visual{border-top-color:rgba(171,211,192,.38)!important}.hero-grid{background:linear-gradient(90deg,transparent 24.8%,rgba(171,211,192,.2) 25%,transparent 25.2%,transparent 49.8%,rgba(171,211,192,.2) 50%,transparent 50.2%,transparent 74.8%,rgba(171,211,192,.2) 75%,transparent 75.2%),linear-gradient(0deg,transparent 49.5%,rgba(171,211,192,.2) 50%,transparent 50.5%)!important}.hero-block{background:#dfeee6!important}.hero-block:after{color:#123126!important}.hero-tag{color:#a9cbbb!important}
.section.white{background:#fff!important}.section.gray{background:#e7f0eb!important}.eyebrow{color:#39745c!important}.section h2{color:#123126!important}.section h2 em{color:#2f8061!important}.lead{color:#52685f!important}.features{border-top-color:#176b4d!important}.feature{border-color:#d4e1da!important}.feature .num,.tool .num{color:#39745c!important}.feature h3,.tool h3{color:#123126!important}.feature p,.tool p{color:#60736b!important}.feature a{color:#176b4d!important;border-bottom-color:#176b4d!important}
.blackband{background:linear-gradient(135deg,#0b2b21,#123f30)!important}.blackband .eyebrow{color:#83b39b!important}.blackband h2{color:#f5faf7!important}.blackband h2 em{color:#a9d4bd!important}.blackband p,.step span{color:#c6d9d0!important}.steps{border-top-color:#4d7865!important}.step{border-bottom-color:#315b4a!important}.step b{color:#82ae98!important}.step strong{color:#fff!important}
.demo-card{border-color:#176b4d!important;box-shadow:18px 18px 0 #0b2b21!important}.demo-card .mini-label{color:#39745c!important}.demo-card h3{color:#123126!important}.demo-card p{color:#60736b!important}.question{border-color:#c6d9d0!important;background:#f0f6f2!important}.demo-card button{background:#176b4d!important}
.tools{border-top-color:#176b4d!important}.tool{border-color:#d4e1da!important}.login-box{border-color:#176b4d!important;box-shadow:14px 14px 0 #0b2b21!important}.login-box h3{color:#123126!important}.login-box input{border-color:#c1d4ca!important;background:#f8fbf9!important}.login-box button{border-color:#176b4d!important;color:#123126!important}.login-box .primary{background:#176b4d!important;color:#fff!important}.footer{background:#fff!important;border-top-color:#d4e1da!important}.footer-brand{color:#123126!important}.footer h4{color:#39745c!important}.footer a,.footer p{color:#60736b!important}.copyright{border-top-color:#d4e1da!important}
@media(max-width:800px){.hero{background:linear-gradient(180deg,rgba(5,30,22,.97),rgba(7,45,32,.78)),url('assets/offshore-bg.jpg') center/cover!important;min-height:720px!important}.hero h1{font-size:68px!important}.demo-card{box-shadow:10px 10px 0 #0b2b21!important}.login-box{box-shadow:8px 8px 0 #0b2b21!important}.navcta{font-size:9px!important}}
`;
    document.head.appendChild(s);
  }
})();
